# Generated by Django 5.1.4 on 2025-05-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_content_message_text_remove_message_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yubor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
