# Generated by Django 5.1.4 on 2025-05-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_yubor'),
    ]

    operations = [
        migrations.AddField(
            model_name='yubor',
            name='shaxar',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yubor',
            name='tel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yubor',
            name='yashash',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
