# Generated by Django 5.2.1 on 2025-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_yubor_shaxar_yubor_tel_yubor_yashash'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
