# Generated by Django 5.1.4 on 2025-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sana',
            field=models.CharField(max_length=120),
        ),
    ]
