# Generated by Django 5.1.4 on 2025-05-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contactsize_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSize',
        ),
    ]
