# Generated by Django 5.1.4 on 2025-05-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_contactsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.contact')),
            ],
        ),
    ]
