# Generated by Django 5.1.4 on 2025-05-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSize',
        ),
    ]
