# Generated by Django 5.1.4 on 2025-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dostavka_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozvarat_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='meida/')),
            ],
        ),
    ]
