# Generated by Django 5.1.4 on 2025-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_imagess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zvezdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(upload_to='meida/')),
                ('img_2', models.ImageField(upload_to='meida/')),
                ('img_3', models.ImageField(upload_to='meida/')),
            ],
        ),
    ]
