# Generated by Django 5.1.4 on 2025-05-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_zvezdi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zvezdi',
            old_name='img_1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='zvezdi',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='zvezdi',
            name='img_3',
        ),
    ]
