# Generated by Django 5.1.4 on 2025-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_img_1_zvezdi_img_remove_zvezdi_img_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvezdi',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
