# Generated by Django 5.1.4 on 2025-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_zvezdi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Avatar rasmi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Bahosi (1-5)')),
                ('text', models.TextField(verbose_name='Izoh matni')),
            ],
        ),
    ]
