# Generated by Django 5.1.4 on 2025-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
