# Generated by Django 5.1.4 on 2025-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_contact_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='discount_price',
            field=models.CharField(max_length=100),
        ),
    ]
