# Generated by Django 5.1.4 on 2025-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_imagesrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='discount_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.IntegerField(),
        ),
    ]
