# Generated by Django 5.1.4 on 2025-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_contact_discount_price_alter_contact_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='yubor',
            name='razmer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
