# Generated by Django 5.1.4 on 2025-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_yubor_razmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
