# Generated by Django 5.1.4 on 2025-06-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_contact_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='discount_percent',
        ),
    ]
