# Generated by Django 5.1.4 on 2025-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_size_contactsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
