# Generated by Django 5.1.4 on 2025-06-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_size_contact_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
