# Generated by Django 5.1.4 on 2025-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_contact_sizes_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
