# Generated by Django 5.1.4 on 2025-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_contact_img2_alter_contact_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesrk',
            name='name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagesrk',
            name='name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagesrk',
            name='name3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
