# Generated by Django 5.1.1 on 2025-07-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_imagesrk_name1_imagesrk_name2_imagesrk_name3'),
    ]

    operations = [
        migrations.AddField(
            model_name='yubor',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yubor_info', to='main.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yubor',
            name='razmer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yubor',
            name='tel',
            field=models.CharField(max_length=20),
        ),
    ]
