# Generated by Django 5.1.4 on 2025-03-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('background_img', models.ImageField(upload_to='media/')),
                ('right_img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
