# Generated by Django 5.1.4 on 2025-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Small_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pirce', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
