# Generated by Django 5.1.4 on 2025-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_small_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discount_price', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
