# Generated by Django 5.1.4 on 2025-03-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discount_price', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
                ('card_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card_two')),
            ],
        ),
    ]
