# Generated by Django 5.1.4 on 2025-03-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card_additional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card_additional',
        ),
    ]
