# Generated by Django 5.1.4 on 2025-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_card_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes_three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discount_price', models.CharField(max_length=50)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
