# Generated by Django 5.1.4 on 2025-03-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_home',
            name='right_img',
        ),
        migrations.RemoveField(
            model_name='index_home',
            name='text',
        ),
        migrations.RemoveField(
            model_name='index_home',
            name='title',
        ),
    ]
