# Generated by Django 5.1.4 on 2025-03-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_index_home_right_img_remove_index_home_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
