# Generated by Django 5.1.4 on 2025-03-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blognew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('color', models.CharField(choices=[('#586882', 'Blue Gray'), ('#505050', 'Dark Gray'), ('#73707a', 'Gray'), ('#c7bb9b', 'Beige')], default='#505050', max_length=7)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5)),
                ('card_number', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='media/')),
                ('img2', models.ImageField(upload_to='media/')),
                ('img3', models.ImageField(upload_to='media/')),
                ('img4', models.ImageField(upload_to='media/')),
                ('card_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card_two')),
            ],
        ),
    ]
