# Generated by Django 5.1.4 on 2025-03-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_single_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_card',
            name='card_two',
        ),
        migrations.AddField(
            model_name='card_two',
            name='single_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.single_card'),
            preserve_default=False,
        ),
    ]
