# Generated by Django 5.1.4 on 2025-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_single_card_card_two_card_two_single_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_two',
            name='single_card',
        ),
    ]
