# Generated by Django 5.1.4 on 2025-03-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_card_two_single_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Single_Card',
        ),
    ]
