# Generated by Django 5.0.3 on 2025-05-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_single_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card_two',
            new_name='Card',
        ),
    ]
