# Generated by Django 5.0.3 on 2025-05-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_card_two_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Contact',
        ),
    ]
