# Generated by Django 5.0.3 on 2025-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_card_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xatolik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Nike_reklama',
        ),
        migrations.DeleteModel(
            name='Shoes_three',
        ),
        migrations.DeleteModel(
            name='Small_card',
        ),
    ]
