# Generated by Django 5.2 on 2025-05-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_xatolik_delete_nike_reklama_delete_shoes_three_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Small',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
