# Generated by Django 5.2 on 2025-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='small',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
