# Generated by Django 5.2 on 2025-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_small_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img1',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='img2',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='img3',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='img4',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
