# Generated by Django 5.0.3 on 2025-05-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_product_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contact'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
