# Generated by Django 5.0.3 on 2025-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_order_orderitem_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='discount_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.IntegerField(),
        ),
    ]
