# Generated by Django 5.0.3 on 2025-05-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_contact_discount_price_alter_contact_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
